server:
  port: 8080
  servlet:
    context-path: /identity

cloudinary:
  cloud-name: dnvtmbmne
  api-key: 761622624158786
  api-secret: kE2b5NITYcKlPzvUoVUb-hB9DII
  secure: true
  upload-preset: null

socketio:
  port: 9099
spring:
  datasource:
    url: "jdbc:mysql://database-1.ctya60eks8ps.ap-southeast-2.rds.amazonaws.com:3306/db_club?useSSL=true&requireSSL=true"
    username: admin
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB           # Giới hạn kích thước file upload
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyenvietmanh1409@gmail.com
    password: cjts ypre fugz hrqh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp
          rset: true

jwt:
  signerKey: "N/qa57r32pqMpmi5PxhHdGMVCI+MgTXPiw83/20xI56B1ij3mMgzpckvznpICkbj"
  valid-duration: 36000 # in second 1h
  refreshable-duration: 360000 # in seconds 10h
#  valid-duration: 3600 # in second 1h
#  refreshable-duration: 36000 # in seconds 10h

